version: 2
registries:
  npm-registry-mmrepo-jfrog-io-mmrepo-npm-virtual:
    type: npm-registry
    url: https://mmrepo.jfrog.io/mmrepo/npm-virtual
    username: "${{secrets.NPM_REGISTRY_MMREPO_JFROG_IO_MMREPO_NPM_VIRTUAL_USERNAME}}"
    password: "${{secrets.NPM_REGISTRY_MMREPO_JFROG_IO_MMREPO_NPM_VIRTUAL_PASSWORD}}"
  npm-registry-mmrepo-jfrog-io-mmrepo-api-npm-npm-virtual:
    type: npm-registry
    url: https://mmrepo.jfrog.io/mmrepo/api/npm/npm-virtual
    username: "${{secrets.NPM_REGISTRY_MMREPO_JFROG_IO_MMREPO_API_NPM_NPM_VIRTUAL_USERNAME}}"
    password: "${{secrets.NPM_REGISTRY_MMREPO_JFROG_IO_MMREPO_API_NPM_NPM_VIRTUAL_PASSWORD}}"
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: chalk
    versions:
    - 4.1.0
  registries:
  - npm-registry-mmrepo-jfrog-io-mmrepo-npm-virtual
  - npm-registry-mmrepo-jfrog-io-mmrepo-api-npm-npm-virtual
  - npm-registry-npm-pkg-github-com
